### PR TITLE
Fix for wrong enum value issue; Remove unnecessary apostrophes

### LINKED ISSUE #40: Wrong conversion for enum type
During conversion from object to value for enum type, mapper adds unnecessary apostrophes to enum value

### PR DESCRIPTION
**Pull request by newagewriter**

### CODE REVIEW

File: lib/src/main/java/com/newagewriter/processor/mapper/AbstractMapper.kt [hunk 1]
```diff
@@ -49,17 +49,18 @@ abstract class AbstractMapper<T>(
 
     protected fun getValue(value: Any?): Any? {
         return value?.let { v ->
-            getConverter(value.javaClass)?.toSimpleValue(v) ?: when (v) {
+            val any = getConverter(value.javaClass)?.toSimpleValue(v) ?: when (v) {
```
Comment (labiod) [inline lib/src/main/java/com/newagewriter/processor/mapper/AbstractMapper.kt]: unnecessary any variable

**Review by labiod — APPROVED** [review]
