### PR TITLE
Fix issue with companion object and static fields in data class annot…

### LINKED ISSUE #82: Issue: Companion object in data model
If Data model contains companion object, generated mapper apply companion object fields to list of class fields

### PR DESCRIPTION
**Pull request by labiod**
…ate with @Mapper

### CODE REVIEW

File: lib/src/main/java/io/github/newagewriter/processor/generator/MapperGenerator.kt [hunk 1]
```diff
@@ -61,16 +62,19 @@ class MapperGenerator private constructor() {
         val mapperName = el.simpleName
 
         val fieldsName = getFields(el).filter { e ->
+            ProcessorLogger.logD("[KB]", "element: ${e.modifiers}")
```
Comment (newagewriter) [inline lib/src/main/java/io/github/newagewriter/processor/generator/MapperGenerator.kt]: remove this logs

**Review by newagewriter — CHANGES_REQUESTED** [review]

**Review by newagewriter — APPROVED** [review]
